### ISSUE TITLE
No way to close or disconnect the KiteTicker websocket API

### ISSUE THREAD

**Issue by selvakn** [rainmattertech/kiteconnectjs#1]
At the exit of my program, as a good practise, I want to disconnect and release the websocket connection established by the KiteTicker. But there is no API exposed to do that!

**Comment by vividvilla** [comment]
Will add method to close the WebSocket connection.

**Comment by selvakn** [comment]
@vividvilla : Any update on this?

**Comment by vividvilla** [comment]
@selvakn Added a method called [disconnect](https://github.com/rainmattertech/kiteconnectjs/blob/master/lib/ticker.js#L253) to version _**1.1.0**_. Its also updated in npm repo so you can directly upgrade your npm package.

**Comment by selvakn** [comment]
I hope you are also going to make a new release, so that it can be used

**Comment by vividvilla** [comment]
@selvakn Its already released you can update your package with npm.
