### ISSUE TITLE
Nodejs requestAccessToken throws error Invalid session credentials, TokenException

### ISSUE THREAD

**Issue by arshmakker** [rainmattertech/kiteconnectjs#3]
Here are the steps to reproduce the issue.

1. via postman or plain vanila browser console, get the request_token via https://api.kite.trade/connect/login?api_key=my_apikey.
2. use the "request_token", "api_secret" in the function kc.requestAccessToken

This always throws the error: 
```
 { status: 'error',
  message: 'Invalid session credentials',
  error_type: 'TokenException' }
```

I am not sure, if I am getting the request_token incorrectly? or if there is something wrong with the response?

**Comment by vividvilla** [comment]
I just checked with the test script and it seems to be working fine. Please check if you are setting your correct `api_key` while initializing and `api_secret` while calling `request_token`.

Note that you need to create Kite connect app to access the api, Kite publisher api_key won't work.

**Comment by arshmakker** [comment]
I did recheck the code, the api_secret and api_key are correct. I also rechecked the request_token was also correct.

Not sure If i could share the api_key etc here for you to check?

**Comment by vividvilla** [comment]
@arshmakker Please share your `api_key` here.

**Comment by vividvilla** [comment]
@arshmakker I found your app and it is Kite Connect app only so you should be able to get `access_token`. Let me test your app with my test scripts and get back to you.

**Comment by vividvilla** [comment]
I just tested your app and it seems to be working fine. I guess you are not getting the right `request_token`. You should be getting it once you login successfully from here  - `https://api.kite.trade/connect/login?api_key=my_apikey`

**Comment by arshmakker** [comment]
hi Vivid,

It worked this time, the problem was i was signed on in Firefox and also was trying to do POSTMAN, which works on chrome. So I guess simultaneous multiple logins are not allowed.

Thanks Dude 👍 

Could i ask another question, I would like to create an app for my clients -- an admin app, where can i get access to such an api that I get access to multiple set of clients?

regards
Arsh

**Comment by vividvilla** [comment]
Request token can be exchanged only once and should be used within 5 mins of the generation. If you want to open up your app to multiple clients then you can speak with our team here - `talk@rainmatter.com`
