### ISSUE TITLE
Add support for Postback(webhooks)

### ISSUE THREAD

**Issue by sivamgr** [rainmattertech/kiteconnectjs#4]
https://kite.trade/docs/connect/v1/?shell#postback-webhooks

**Comment by vividvilla** [comment]
You can just run a simple web server which accepts the POST request and validates the checksum.

**Comment by sivamgr** [comment]
Agreed, the API user can run a webserver of his choice.  Does it make sense to, have an helper API included in kiteconnect, to validate the POST content. 

kc.validatePostback(content).then(r){
// content validated. add code to handle content here...
}
.catch(err){
 //discard bad post-message
}

**Comment by vividvilla** [comment]
Yeah seems like a valid request. Will add it as a feature request.

**Comment by vividvilla** [comment]
Thanks for your feedback, it's added in version 1.2.2 - https://github.com/rainmattertech/kiteconnectjs/releases/tag/v1.2.2
