### ISSUE TITLE
Cancelling regular order doesnt work

### ISSUE THREAD

**Issue by anandanand84** [rainmattertech/kiteconnectjs#7]
Cancelling regular order fails with 404 exception 

{"status":"fail","reason":"404 - \"{\\\"status\\\": \\\"error\\\", \\\"message\\\": \\\"Route not found\\\", \\\"error_type\\\": \\\"GeneralException\\\"}\""}

**Comment by vividvilla** [comment]
@anandanand84 This was fixed while back (#5) but wasn't updated in NPM. Now the package has been updated to version `1.1.1` with the fixes. Please update your package to latest version.
